runtime: php83
entrypoint: serve login.php

handlers:
# Serve images as static resources.
- url: /img
  static_dir: img

# Serve CSS file as a static resource.
- url: /(style\.css)
  static_files: style.css
  upload: style.css

# Serve PHP scripts.
- url: /(.+\.php)$
  script: \1

# Catch-all handler to serve a PHP script for every URL
- url: /.*
  script: index.php
